name: covid19-vaccine-slot-tracker
channels:
- defaults
- conda-forge
- ericmjl
dependencies:
- python=3.9.5
- conda
- scikit-learn
- scipy
- pandas
- numpy
- matplotlib
- pip
- pylint
- pydocstyle
- flake8
- black
- hvplot
- bokeh
- holoviews
- pip:
  - streamlit
